Repository PLUS-POSTECH/study.plus.or.kr, pull requests merged in 2018-07, with the labels that each got.

#18 Features/problems revision
  requirements.txt
  src/plus_study/settings.py
  src/plus_study/urls.py
  src/problem/helpers/__init__.py
  src/problem/helpers/problem_info.py
  src/problem/helpers/score.py
  src/problem/migrations/0003_auto_20180621_1707.py
  src/problem/migrations/0004_populate_attachment_field.py
  src/problem/migrations/0005_auto_20180621_1711.py
  src/problem/migrations/0006_auto_20180703_1701.py
  src/problem/models.py
  src/problem/templates/problem/get.html
  src/problem/templates/problem/list.html
  src/problem/templates/problem/rank.html
  src/problem/urls.py
  src/problem/views.py
  src/seminar/migrations/0002_auto_20180621_1559.py
  src/seminar/migrations/0003_populate_attachment_field.py
  src/seminar/migrations/0004_auto_20180621_1606.py
  src/seminar/migrations/0005_auto_20180703_1701.py
  src/seminar/models.py
  src/seminar/templates/seminar/list.html
  src/seminar/urls.py
  src/seminar/views.py
  src/website/migrations/0005_auto_20180621_1659.py
  src/website/static/semantic/semantic.min.css
  src/website/static/semantic/semantic.min.js
  src/website/static/semantic/themes/default/assets/fonts/brand-icons.eot
  src/website/static/semantic/themes/default/assets/fonts/brand-icons.svg
  src/website/static/semantic/themes/default/assets/fonts/brand-icons.ttf
  src/website/static/semantic/themes/default/assets/fonts/brand-icons.woff
  src/website/static/semantic/themes/default/assets/fonts/brand-icons.woff2
  src/website/static/semantic/themes/default/assets/fonts/icons.eot
  src/website/static/semantic/themes/default/assets/fonts/icons.svg
  src/website/static/semantic/themes/default/assets/fonts/icons.ttf
  src/website/static/semantic/themes/default/assets/fonts/icons.woff
  src/website/static/semantic/themes/default/assets/fonts/icons.woff2
  src/website/static/semantic/themes/default/assets/fonts/outline-icons.eot
  src/website/static/semantic/themes/default/assets/fonts/outline-icons.svg
  src/website/static/semantic/themes/default/assets/fonts/outline-icons.ttf
  src/website/static/semantic/themes/default/assets/fonts/outline-icons.woff
  src/website/static/semantic/themes/default/assets/fonts/outline-icons.woff2
  src/website/templates/base.html
  src/website/urls.py
  src/website/views.py
Labels: model, refactoring, view logic

#32 Features/QnA
  src/problem/admin.py
  src/problem/helpers/score.py
  src/problem/migrations/0004_populate_attachment_field.py
  src/problem/migrations/0007_auto_20180711_1651.py
  src/problem/models.py
  src/problem/templates/problem/get.html
  src/problem/templates/problem/list.html
  src/problem/templates/problem/question.html
  src/problem/urls.py
  src/problem/views.py
  src/seminar/migrations/0003_populate_attachment_field.py
Labels: new feature

#34 Features/ci
  .circleci/config.yml
  .flake8
  .pylintrc
  src/problem/admin.py
  src/problem/helpers/score.py
  src/problem/models.py
  src/problem/views.py
  src/seminar/admin.py
  src/website/admin.py
  src/website/views.py
Labels: refactoring

#36 Apply allow_question field
  src/problem/templates/problem/get.html
  src/problem/views.py
Labels: new feature

#37 added simple notification
  .circleci/config.yml
  ci_requirements.txt
  src/problem/migrations/0008_problemlist_announcement.py
  src/problem/models.py
  src/problem/templates/problem/list.html
  src/problem/views.py
Labels: new feature

#38 Features/sort
  src/problem/templates/problem/list.html
  src/problem/views.py
  src/seminar/templates/seminar/list.html
  src/seminar/views.py
Labels: new feature

#41 결국 굴복해서 플러스 부엉이로 했습니다
  src/website/static/plus.png
  src/website/templates/base.html
Labels: ux / ui

#42 Home/notification
  src/problem/templates/problem/question.html
  src/website/admin.py
  src/website/migrations/0006_notification.py
  src/website/models.py
  src/website/templates/index.html
  src/website/urls.py
  src/website/views.py
Labels: ux / ui
